export const experincesData = [
  {
    id: "abjhbscf",
    day: "05",
    day_of_week: "THUR",
    events: [
      {
        id: "abcsckn",
        cover_photo: "/images/joeboy.png",
        day: "05",

        day_of_week: "THUR",
        time: "9",
        time_type: "AM",
        name: "JOEBOY LIVE IN CONCERT",
        venue: "Jagor center",
      },
      {
        id: "abhhncc",
        cover_photo: "/images/fireboy.png",
        day: "05",

        day_of_week: "THUR",
        time: "9",
        time_type: "AM",
        name: "FIREBOY UNIVERSITY TOUR",
        venue: "Jagor center",
      },
      {
        id: "ab0pc",
        cover_photo: "/images/goodgirlla.png",
        day: "05",

        day_of_week: "THUR",
        time: "9",
        time_type: "AM",
        name: "FEMME",
        venue: "Jagor center",
      },
    ],
  },
  {
    id: "abjhbscfjdfv",
    day: "06",
    day_of_week: "FRI",
    events: [
      {
        id: "abec",
        cover_photo: "/images/goodgirlla.png",
        day: "06",
        day_of_week: "FRI",
        time: "9",
        time_type: "AM",
        name: "FEMME",
        venue: "Jagor center",
      },
      {
        id: "abcr",
        cover_photo: "/images/joeboy.png",
        day: "06",
        day_of_week: "FRI",
        time: "9",
        time_type: "AM",
        name: "JOEBOY LIVE IN CONCERT",
        venue: "Jagor center",
      },
      {
        id: "ab7c",
        cover_photo: "/images/fireboy.png",
        day: "06",
        day_of_week: "FRI",
        time: "9",
        time_type: "AM",
        name: "FIREBOY UNIVERSITY TOUR",
        venue: "Jagor center",
      },
    ],
  },
  {
    id: "abjhbsdfccf",
    day: "07",
    day_of_week: "SAT",
    events: [
      {
        id: "abcjf",
        cover_photo: "/images/fireboy.png",
        day: "07",
        day_of_week: "SAT",
        time: "9",
        time_type: "AM",
        name: "FIREBOY UNIVERSITY TOUR",
        venue: "Jagor center",
      },
      {
        id: "aboec",
        cover_photo: "/images/joeboy.png",
        day: "07",
        day_of_week: "SAT",
        time: "9",
        time_type: "AM",
        name: "JOEBOY LIVE IN CONCERT",
        venue: "Jagor center",
      },
      {
        id: "abc09",
        cover_photo: "/images/goodgirlla.png",
        day: "07",
        day_of_week: "SAT",
        time: "9",
        time_type: "AM",
        name: "FEMME",
        venue: "Jagor center",
      },
    ],
  },
];
